# Generated by Django 4.2.23 on 2025-07-12 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='clinic_admin',
            field=models.OneToOneField(limit_choices_to={'role': 'clinic_admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_clinic', to=settings.AUTH_USER_MODEL),
        ),
    ]
