# Generated by Django 4.2.23 on 2025-07-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='doctors',
            field=models.ManyToManyField(blank=True, related_name='services_offered', to='doctors.doctor'),
        ),
    ]
