# Generated by Django 4.2.23 on 2025-07-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'در انتظار تأیید'), ('confirmed', 'تأیید شده'), ('cancelled', 'لغو شده'), ('completed', 'انجام شده')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('booking_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-start_time'],
            },
        ),
    ]
